Add missing printf function attribute
Reported by clang:

    ../src/share/log.c:812:35: error: format string is not a string literal [-Werror,-Wformat-nonliteral]
      812 |                 r = vasprintf(&m, format, aq);
          |                                   ^~~~~~